"""add group_id to transcriptions

Revision ID: b711a060b14e
Revises: f72f14573915
Create Date: 2025-10-11 11:18:44.616086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b711a060b14e"
down_revision: Union[str, None] = "f72f14573915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcriptions", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transcriptions", "groups", ["group_id"], ["group_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transcriptions", type_="foreignkey")
    op.drop_column("transcriptions", "group_id")
    # ### end Alembic commands ###
