"""drop model

Revision ID: fbcffe45cfb1
Revises: f7fc5983e988
Create Date: 2025-06-08 23:16:42.801436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbcffe45cfb1"
down_revision: Union[str, None] = "f7fc5983e988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcriptions", "model")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcriptions", sa.Column("model", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
