"""add is_uncategorized to group

Revision ID: 8ea88400f5d9
Revises: c134abd3c20f
Create Date: 2025-06-14 21:56:02.340902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ea88400f5d9"
down_revision: Union[str, None] = "c134abd3c20f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column(
            "is_uncategorized",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.alter_column(
        "transcriptions",
        "error_message",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transcriptions",
        "error_message",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.drop_column("groups", "is_uncategorized")
    # ### end Alembic commands ###
