"""add user

Revision ID: 3802622c2d03
Revises: fbcffe45cfb1
Create Date: 2025-06-12 00:09:49.345950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3802622c2d03'
down_revision: Union[str, None] = 'fbcffe45cfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Integer(), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account')
    )
    op.add_column('transcriptions', sa.Column('transcription_id', sa.Integer(), nullable=False))
    op.add_column('transcriptions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.alter_column('transcriptions', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transcriptions', 'srt_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transcriptions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transcriptions', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('transcriptions', 'result',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('transcriptions', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transcriptions', 'completed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transcriptions', 'estimated_completion_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transcriptions', 'extra_metadata',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.drop_index(op.f('ix_transcriptions_created_at'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_task_id'), table_name='transcriptions')
    op.create_unique_constraint(None, 'transcriptions', ['task_id'])
    op.drop_column('transcriptions', 'progress')
    op.drop_column('transcriptions', 'id')
    op.drop_column('transcriptions', 'current_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('current_step', sa.VARCHAR(), nullable=True))
    op.add_column('transcriptions', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('transcriptions', sa.Column('progress', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transcriptions', type_='unique')
    op.create_index(op.f('ix_transcriptions_task_id'), 'transcriptions', ['task_id'], unique=1)
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    op.create_index(op.f('ix_transcriptions_created_at'), 'transcriptions', ['created_at'], unique=False)
    op.alter_column('transcriptions', 'extra_metadata',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('transcriptions', 'estimated_completion_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transcriptions', 'completed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transcriptions', 'started_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transcriptions', 'result',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('transcriptions', 'error_message',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('transcriptions', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transcriptions', 'srt_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transcriptions', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transcriptions', 'updated_at')
    op.drop_column('transcriptions', 'transcription_id')
    op.drop_table('users')
    # ### end Alembic commands ###
