"""add user_id to transcriptions

Revision ID: 44965188c973
Revises: b711a060b14e
Create Date: 2025-11-13 11:27:36.994522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44965188c973"
down_revision: Union[str, None] = "b711a060b14e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcriptions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transcriptions", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transcriptions", type_="foreignkey")
    op.drop_column("transcriptions", "user_id")
    # ### end Alembic commands ###
