"""add summary transcription_text

Revision ID: 5d813c94d75b
Revises: a6dc1cc12be4
Create Date: 2025-06-15 01:22:28.812691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d813c94d75b"
down_revision: Union[str, None] = "a6dc1cc12be4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcriptions", sa.Column("summary", sa.TEXT(), nullable=True))
    op.add_column(
        "transcriptions", sa.Column("transcription_text", sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcriptions", "transcription_text")
    op.drop_column("transcriptions", "summary")
    # ### end Alembic commands ###
