"""add speakers and transcript_segments

Revision ID: 594b777dea02
Revises: 4d6575f1afdb
Create Date: 2025-07-05 15:19:31.737920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "594b777dea02"
down_revision: Union[str, None] = "4d6575f1afdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speakers",
        sa.Column("speaker_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transcription_id", sa.Integer(), nullable=False),
        sa.Column("speaker_identifier", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["transcription_id"],
            ["transcriptions.transcription_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("speaker_id"),
    )
    op.create_table(
        "transcript_segments",
        sa.Column("segment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transcription_id", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.Integer(), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=20), nullable=False),
        sa.Column("end_time", sa.String(length=20), nullable=False),
        sa.Column("start_seconds", sa.Float(), nullable=False),
        sa.Column("end_seconds", sa.Float(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column(
            "is_edited", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"], ["speakers.speaker_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["transcription_id"],
            ["transcriptions.transcription_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("segment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcript_segments")
    op.drop_table("speakers")
    # ### end Alembic commands ###
