"""add tags speaks to transcriptions

Revision ID: a6dc1cc12be4
Revises: 8ea88400f5d9
Create Date: 2025-06-15 00:24:03.816027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6dc1cc12be4'
down_revision: Union[str, None] = '8ea88400f5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('transcription_title', sa.String(length=255), nullable=False))
    op.add_column('transcriptions', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('transcriptions', sa.Column('speaks', sa.JSON(), nullable=True))
    op.add_column('transcriptions', sa.Column('audio_duration', sa.Float(), nullable=True))
    op.drop_column('transcriptions', 'updated_at')
    op.drop_column('transcriptions', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('error_message', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('transcriptions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('transcriptions', 'audio_duration')
    op.drop_column('transcriptions', 'speaks')
    op.drop_column('transcriptions', 'tags')
    op.drop_column('transcriptions', 'transcription_title')
    # ### end Alembic commands ###
