"""transcriptions user_id can be null

Revision ID: 13e2fe9143b2
Revises: 09db9a9d7d35
Create Date: 2025-12-31 11:20:31.051432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e2fe9143b2'
down_revision: Union[str, None] = '09db9a9d7d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transcriptions_user_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptions_user_id_fkey'), 'transcriptions', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
