"""update role

Revision ID: f8385992dcf7
Revises: 44965188c973
Create Date: 2025-11-17 11:38:05.517257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8385992dcf7"
down_revision: Union[str, None] = "44965188c973"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groups",
        "role",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=15),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groups",
        "role",
        existing_type=sa.String(length=15),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
        existing_server_default=sa.text("'user'::character varying"),
    )
    # ### end Alembic commands ###
